import {demographyMetrics,demographicLabel} from '../utils/demography';
import {isIncomeMetric,metricYear} from '../utils/income';
import type {District,State} from '../types';
import {pearson,spearman,linear,quantile,regression} from '../analysis/statistics';
import {finite,weightedMean,sum} from '../utils/data';
import {escapeHtml as e,number,percent} from '../utils/format';
import {parties} from '../maps/palette';
export function renderAnalysis(root:HTMLElement,rows:District[],national:District[],s:State,select:(id:string)=>void){
 const key=s.analysisY==='turnout'?'turnout_pct':`pct_${s.party}`,ylabel=s.analysisY==='turnout'?'Participación electoral':`Voto ${s.party}`;
 const xkey=s.analysisX??'foreign_background_pct',income=isIncomeMetric(xkey),xlabel=demographicLabel(xkey),xunit=income?'miles de SEK/año · precios 2024':'%',xValue=(d:District)=>(d[xkey] as number)/(income?1000:1),xFormat=(v:number)=>income?number(v,1)+' kSEK':percent(v);
 const points=rows.filter(d=>finite(d[xkey])&&finite(d[key]));const x=points.map(xValue),y=points.map(d=>d[key] as number),fit=linear(x,y),r=pearson(x,y),rho=spearman(x,y);
 const xMin=income?Math.min(0,Math.floor(Math.min(...x,0)/100)*100):0,xMax=income?Math.max(100,Math.ceil(Math.max(...x,0)/100)*100):100,yMax=Math.min(100,Math.max(10,Math.ceil(Math.max(...y,0)/10)*10));
 const plotX=(v:number)=>65+(v-xMin)/(xMax-xMin)*710,plotY=(v:number)=>350-v/yMax*300;
 const xTicks=Array.from({length:6},(_,i)=>xMin+(xMax-xMin)*i/5),yTicks=Array.from({length:6},(_,i)=>yMax*i/5);
 const partyColor=parties.find(p=>p.id===s.party)?.color??'#2475b4';
 const controlDefs=[['foreign_background_pct',`Origen extranjero (${rows[0]?.demography_year??s.year})`],['higher_education_pct',`Educación postsecundaria, 25–64 (${rows[0]?.education_year??s.year})`],['employment_pct',`Empleo, 20–64 (${rows[0]?.employment_year??'sin dato'})`],['mean_net_income',`Renta neta media anual ≈ (${rows[0]?.income_year??'sin dato'}; SEK 2024)`],['age','Edad'],['urban_density','Densidad urbana']];
 root.innerHTML=`<div class="analysis-intro"><div><span class="eyebrow">ASOCIACIONES TERRITORIALES</span><h2>${e(ylabel)} · ${e(xlabel)}</h2><p>Cada punto es un distrito. Indicador estimado · ${metricYear(rows[0],xkey)}.</p></div><div class="analysis-controls"><label>Eje X<select id="analysis-x">${demographyMetrics.filter(([k])=>k!=='common_origin').map(([k,text])=>`<option value="${k}" ${k===xkey?'selected':''}>${e(text)}</option>`).join('')}</select></label><label>Eje Y<select id="analysis-y"><option value="party" ${s.analysisY==='party'?'selected':''}>Voto al partido</option><option value="turnout" ${s.analysisY==='turnout'?'selected':''}>Participación</option></select></label><label>Tamaño del punto<select id="point-size"><option value="equal" ${s.size==='equal'?'selected':''}>Igual</option><option value="votes" ${s.size==='votes'?'selected':''}>Votos válidos</option></select></label></div></div>
 <div class="stat-strip"><div class="primary-correlation" data-stat="spearman"><span>Spearman ρ · no paramétrica</span><b>${number(rho,3)}</b></div><div><span>Distritos con ambos datos</span><b>${number(points.length)}</b></div><div class="secondary-stat"><span>Pearson r · referencia lineal</span><b>${number(r,3)}</b></div><div class="secondary-stat"><span>Pendiente OLS · ${income?'pp / 1.000 SEK':'pp/pp'}</span><b>${number(fit?.slope,3)}</b></div></div>
 <p class="correlation-caption">Spearman compara el orden de los distritos: +1 indica una tendencia creciente perfecta; −1, decreciente. La línea discontinua es un ajuste lineal OLS.</p><details class="compact-detail"><summary>Cómo leer el gráfico</summary><p class="meta">Spearman mide asociación monótona, sin exigir una relación lineal ni normalidad. Usa rangos medios en los empates. Un valor cercano a cero no descarta relaciones con forma de U. No se calculan pruebas de significación.</p><p class="meta">Correlaciones y recta: cada distrito pesa igual. ${number(rows.length-points.length)} distritos excluidos por datos ausentes. No se calculan con menos de tres casos o variables constantes.</p></details>
 <div class="chart-card">${points.length?`<svg class="scatter" viewBox="0 0 820 415" role="img" aria-label="Dispersión · ${e(xlabel)} / ${e(ylabel)}"><defs><clipPath id="plotClip"><rect x="65" y="50" width="710" height="300"/></clipPath></defs>${yTicks.map(v=>`<line x1="65" x2="775" y1="${plotY(v)}" y2="${plotY(v)}" class="grid-line"/><text x="53" y="${plotY(v)+5}" text-anchor="end">${number(v,1)}</text>`).join('')}${xTicks.map(v=>`<text x="${plotX(v)}" y="373" text-anchor="middle">${number(v,0)}</text>`).join('')}<text x="65" y="27">${e(ylabel)} (%)</text><text x="415" y="403" text-anchor="middle">${e(xlabel)} (${e(xunit)})</text><g clip-path="url(#plotClip)">${points.map(d=>`<circle cx="${plotX(xValue(d))}" cy="${plotY(d[key] as number)}" r="${s.size==='votes'?Math.max(2,Math.min(9,Math.sqrt(d.valid_votes??0)/9)):2.7}" fill="${partyColor}" opacity=".42" data-district="${d.district_id}" tabindex="-1" role="button" aria-label="${e(d.district_name)}"><title>${e(d.district_name)} · ${e(d.municipality_name)}\n${e(xlabel)}: ${xFormat(xValue(d))}\n${e(ylabel)}: ${percent(d[key])}\nVotos válidos: ${number(d.valid_votes)}</title></circle>`).join('')}${fit?`<line x1="65" x2="775" y1="${plotY(fit.intercept+xMin*fit.slope)}" y2="${plotY(fit.intercept+xMax*fit.slope)}" stroke="#172f40" stroke-width="2" stroke-dasharray="7 4"/>`:''}</g></svg>`:'<p class="empty">No hay observaciones completas para estos filtros.</p>'}<p id="point-detail" class="meta" aria-live="polite">Pulsa un punto para ver su distrito.</p></div>
 ${s.year===2026?`<p class="plot-downloads"><span>Gráfico conjunto 2026 · S, V, S+V y S+V+Verdes · origen y voto · inglés</span> <a href="${import.meta.env.BASE_URL}reports/four-plots-2026-English-v8-spearman.png" download>PNG</a> · <a href="${import.meta.env.BASE_URL}reports/four-plots-2026-English-v8-spearman.pdf" download>PDF</a></p>`:''}
 <div class="section-heading"><h2>Voto por indicador seleccionado</h2><label>Ponderación de bins y deciles<select id="weights"><option value="votes" ${s.weight==='votes'?'selected':''}>Ponderar por votos válidos</option><option value="equal" ${s.weight==='equal'?'selected':''}>Cada valdistrikt pesa igual</option></select></label></div><details class="compact-detail"><summary>Cómo se agrupan los distritos</summary><p class="meta">Intervalos fijos: diez puntos porcentuales o 100.000 SEK anuales. El último agrupa los valores superiores. Indicadores estimados. La participación de esta tabla es una media con la ponderación seleccionada.</p></details><div id="bins"></div>
 <h2>Media de voto por decil nacional · ${e(xlabel)}</h2><details class="compact-detail"><summary>Cómo se calculan los deciles</summary><p class="meta">Cortes nacionales fijos. Los empates permanecen juntos; los grupos pueden tener tamaños diferentes o quedar vacíos.</p></details><div id="deciles" class="table-wrap"></div>
 <details class="regression"><summary>Explorar asociaciones con controles socioeconómicos</summary><p><strong>Association conditional on included variables.</strong> Asociaciones condicionadas a las variables incluidas; los coeficientes no son efectos causales. La interpolación y la dependencia espacial limitan la interpretación.</p><fieldset><legend>Variables explicativas · OLS, distritos con casos completos</legend>${controlDefs.map(([k,label])=>{const available=rows.some(d=>finite(d[k]));return `<label><input type="checkbox" name="predictor" value="${k}" ${available?'checked':'disabled'}> ${label}${available?'':' · no disponible'}</label>`;}).join('')}</fieldset><div id="regression-result"></div></details>`;
 const binStep=income?100:10;const bins=Array.from({length:8},(_,i)=>({label:i===7?xFormat(7*binStep)+'+':`${xFormat(i*binStep)}–${xFormat((i+1)*binStep)}`,rows:points.filter(d=>(i===0||xValue(d)>=i*binStep)&&(i===7||xValue(d)<(i+1)*binStep))}));
 const table=(groups:{label:string;rows:District[]}[])=>`<table><thead><tr><th>${e(xlabel)}</th><th>n</th><th>Población ≈</th><th>Participación</th>${['S','SD','M','V','rest'].map(p=>`<th>${p==='rest'?'Resto':p}</th>`).join('')}</tr></thead><tbody>${groups.map(g=>{const vals=['S','SD','M','V'].map(p=>weightedMean(g.rows,`pct_${p}`,s.weight));return `<tr><th>${e(g.label)}</th><td>${number(g.rows.length)}</td><td>${number(sum(g.rows,'population'))}</td><td>${percent(weightedMean(g.rows,'turnout_pct',s.weight))}</td>${vals.map(v=>`<td>${percent(v)}</td>`).join('')}<td>${percent(g.rows.length?100-vals.reduce<number>((a,b)=>a+(b??0),0):null)}</td></tr>`;}).join('')}</tbody></table>`;
 root.querySelector('#bins')!.innerHTML=`<div class="bin-chart" role="img" aria-label="Barras de voto medio por intervalo del indicador">${bins.map(g=>`<div class="bin-row"><span>${g.label}</span><div class="stack">${parties.map(p=>{const v=weightedMean(g.rows,`pct_${p.id}`,s.weight)??0;return `<i style="width:${v}%;background:${p.color}" title="${e(p.name)}: ${percent(v)}"></i>`;}).join('')}</div><small>n = ${number(g.rows.length)}</small></div>`).join('')}</div><div class="party-legend">${parties.map(p=>`<span><i style="background:${p.color}"></i>${p.id}</span>`).join('')}</div><div class="table-wrap">${table(bins)}</div>`;
 const cuts=Array.from({length:9},(_,i)=>quantile(national.filter(d=>finite(d[xkey])).map(xValue),(i+1)/10)??0);
 const deciles=Array.from({length:10},(_,i)=>({label:`${i+1} · ${i===0?'≤ '+xFormat(cuts[0]):i===9?'> '+xFormat(cuts[8]):xFormat(cuts[i-1])+'–'+xFormat(cuts[i])}`,rows:points.filter(d=>{let bin=cuts.findIndex(c=>xValue(d)<=c);if(bin<0)bin=9;return bin===i;})}));
 root.querySelector('#deciles')!.innerHTML=table(deciles);
 root.querySelectorAll<SVGElement>('[data-district]').forEach(c=>{const click=()=>{const d=points.find(d=>d.district_id===c.dataset.district)!;root.querySelector('#point-detail')!.textContent=`${d.district_name} · ${d.municipality_name} | ${xlabel} ${xFormat(xValue(d))} | ${ylabel} ${percent(d[key])} | ${number(d.valid_votes)} votos válidos`;select(d.district_id);};c.addEventListener('click',click);c.addEventListener('keydown',event=>{if(event.key==='Enter')click();});});
 const calculate=()=>{const included=[...root.querySelectorAll<HTMLInputElement>('input[name=predictor]:checked')].map(i=>i.value),complete=points.filter(d=>included.every(k=>finite(d[k]))),result=regression(complete.map(d=>included.map(k=>d[k] as number)),complete.map(d=>d[key] as number));root.querySelector('#regression-result')!.innerHTML=result?`<p>n = ${number(result.n)} · R² = ${number(result.r2,3)} · cada distrito pesa igual.</p><p class="meta">Coeficientes en puntos porcentuales de ${e(ylabel)} por una desviación típica de la variable explicativa, manteniendo las otras constantes. Sin pruebas de significación ni interpretación causal.</p><div class="table-wrap"><table><thead><tr><th>Variable</th><th>Coeficiente</th><th>Desviación típica original</th></tr></thead><tbody><tr><th>Intercepto (predictores centrados)</th><td>${number(result.coefficients[0],3)}</td><td>—</td></tr>${included.map((k,i)=>`<tr><th>${e(controlDefs.find(d=>d[0]===k)?.[1]??k)}</th><td>${number(result.coefficients[i+1],3)}</td><td>${number(result.sd[i],3)}</td></tr>`).join('')}</tbody></table></div>`:'<p>No se puede ajustar: selecciona predictores con variación, suficientes casos completos y sin colinealidad perfecta.</p>';};
 root.querySelectorAll('input[name=predictor]').forEach(input=>input.addEventListener('change',calculate));calculate();
}
