import type {District,State} from '../types';
import {pearson,spearman,linear,quantile,regression} from '../analysis/statistics';
import {finite,weightedMean,sum} from '../utils/data';
import {escapeHtml as e,number,percent} from '../utils/format';
import {parties} from '../maps/palette';
export function renderAnalysis(root:HTMLElement,rows:District[],national:District[],s:State,select:(id:string)=>void){
 const key=s.analysisY==='turnout'?'turnout_pct':`pct_${s.party}`,ylabel=s.analysisY==='turnout'?'Participación electoral':`Voto ${s.party}`;
 const points=rows.filter(d=>finite(d.foreign_background_pct)&&finite(d[key]));const x=points.map(d=>d.foreign_background_pct!),y=points.map(d=>d[key] as number),fit=linear(x,y),r=pearson(x,y),rho=spearman(x,y);
 const plotX=(v:number)=>65+v*7.1,plotY=(v:number)=>350-v*3;
 const partyColor=parties.find(p=>p.id===s.party)?.color??'#2475b4';
 const controlDefs=[['foreign_background_pct',`Origen extranjero (${rows[0]?.demography_year??s.year})`],['higher_education_pct',`Educación postsecundaria, 25–64 (${rows[0]?.education_year??s.year})`],['employment_pct',`Empleo, 20–64 (${rows[0]?.employment_year??'sin dato'})`],['median_income','Renta mediana'],['age','Edad'],['urban_density','Densidad urbana']];
 root.innerHTML=`<div class="analysis-intro"><div><span class="eyebrow">ASOCIACIONES TERRITORIALES</span><h2>${e(ylabel)} y origen extranjero</h2><p>Cada punto es un distrito. Origen estimado.</p></div><div class="analysis-controls"><label>Eje Y<select id="analysis-y"><option value="party" ${s.analysisY==='party'?'selected':''}>Voto al partido</option><option value="turnout" ${s.analysisY==='turnout'?'selected':''}>Participación</option></select></label><label>Tamaño del punto<select id="point-size"><option value="equal" ${s.size==='equal'?'selected':''}>Igual</option><option value="votes" ${s.size==='votes'?'selected':''}>Votos válidos</option></select></label></div></div>
 <div class="stat-strip"><div><span>Distritos con ambos datos</span><b>${number(points.length)}</b></div><div><span>Pearson r</span><b>${number(r,3)}</b></div><div><span>Spearman ρ</span><b>${number(rho,3)}</b></div><div><span>Pendiente OLS · pp/pp</span><b>${number(fit?.slope,3)}</b></div></div>
 <details class="compact-detail"><summary>Cómo leer el gráfico</summary><p class="meta">Correlaciones y recta: cada distrito pesa igual. ${number(rows.length-points.length)} distritos excluidos por datos ausentes. No se calculan con menos de tres casos o variables constantes.</p></details>
 <div class="chart-card">${points.length?`<svg class="scatter" viewBox="0 0 820 415" role="img" aria-label="Dispersión entre origen extranjero y ${e(ylabel)}"><defs><clipPath id="plotClip"><rect x="65" y="50" width="710" height="300"/></clipPath></defs>${[0,20,40,60,80,100].map(v=>`<line x1="65" x2="775" y1="${plotY(v)}" y2="${plotY(v)}" class="grid-line"/><text x="53" y="${plotY(v)+5}" text-anchor="end">${v}</text><text x="${plotX(v)}" y="373" text-anchor="middle">${v}</text>`).join('')}<text x="65" y="27">${e(ylabel)} (%)</text><text x="415" y="403" text-anchor="middle">Utländsk bakgrund · origen extranjero (%)</text><g clip-path="url(#plotClip)">${points.map(d=>`<circle cx="${plotX(d.foreign_background_pct!)}" cy="${plotY(d[key] as number)}" r="${s.size==='votes'?Math.max(2,Math.min(9,Math.sqrt(d.valid_votes??0)/9)):2.7}" fill="${partyColor}" opacity=".42" data-district="${d.district_id}" tabindex="-1" role="button" aria-label="${e(d.district_name)}"><title>${e(d.district_name)} · ${e(d.municipality_name)}\nOrigen extranjero: ${percent(d.foreign_background_pct)}\n${e(ylabel)}: ${percent(d[key])}\nVotos válidos: ${number(d.valid_votes)}</title></circle>`).join('')}${fit?`<line x1="65" x2="775" y1="${plotY(fit.intercept)}" y2="${plotY(fit.intercept+100*fit.slope)}" stroke="#172f40" stroke-width="2" stroke-dasharray="7 4"/>`:''}</g></svg>`:'<p class="empty">No hay observaciones completas para estos filtros.</p>'}<p id="point-detail" class="meta" aria-live="polite">Pulsa un punto para ver su distrito.</p></div>
 <div class="section-heading"><h2>Voto por composición demográfica</h2><label>Ponderación de bins y deciles<select id="weights"><option value="votes" ${s.weight==='votes'?'selected':''}>Ponderar por votos válidos</option><option value="equal" ${s.weight==='equal'?'selected':''}>Cada valdistrikt pesa igual</option></select></label></div><details class="compact-detail"><summary>Cómo se agrupan los distritos</summary><p class="meta">Los intervalos incluyen el límite inferior y excluyen el superior; el último incluye 100 %. Población estimada. La participación de esta tabla es una media con la ponderación seleccionada.</p></details><div id="bins"></div>
 <h2>Media de voto por decil nacional de origen extranjero</h2><details class="compact-detail"><summary>Cómo se calculan los deciles</summary><p class="meta">Cortes nacionales fijos. Los empates permanecen juntos; los grupos pueden tener tamaños diferentes o quedar vacíos.</p></details><div id="deciles" class="table-wrap"></div>
 <details class="regression"><summary>Explorar asociaciones con controles socioeconómicos</summary><p><strong>Association conditional on included variables.</strong> Asociaciones condicionadas a las variables incluidas; los coeficientes no son efectos causales. La interpolación y la dependencia espacial limitan la interpretación.</p><fieldset><legend>Variables explicativas · OLS, distritos con casos completos</legend>${controlDefs.map(([k,label])=>{const available=rows.some(d=>finite(d[k]));return `<label><input type="checkbox" name="predictor" value="${k}" ${available?'checked':'disabled'}> ${label}${available?'':' · no disponible'}</label>`;}).join('')}</fieldset><div id="regression-result"></div></details>`;
 const bins=Array.from({length:8},(_,i)=>({label:i===7?'70 %+':`${i*10}–${(i+1)*10} %`,rows:points.filter(d=>d.foreign_background_pct!>=i*10&&(i===7||d.foreign_background_pct!<(i+1)*10))}));
 const table=(groups:{label:string;rows:District[]}[])=>`<table><thead><tr><th>Origen extranjero</th><th>n</th><th>Población ≈</th><th>Participación</th>${['S','SD','M','V','rest'].map(p=>`<th>${p==='rest'?'Resto':p}</th>`).join('')}</tr></thead><tbody>${groups.map(g=>{const vals=['S','SD','M','V'].map(p=>weightedMean(g.rows,`pct_${p}`,s.weight));return `<tr><th>${e(g.label)}</th><td>${number(g.rows.length)}</td><td>${number(sum(g.rows,'population'))}</td><td>${percent(weightedMean(g.rows,'turnout_pct',s.weight))}</td>${vals.map(v=>`<td>${percent(v)}</td>`).join('')}<td>${percent(g.rows.length?100-vals.reduce<number>((a,b)=>a+(b??0),0):null)}</td></tr>`;}).join('')}</tbody></table>`;
 root.querySelector('#bins')!.innerHTML=`<div class="bin-chart" role="img" aria-label="Barras de voto medio por intervalo de origen extranjero">${bins.map(g=>`<div class="bin-row"><span>${g.label}</span><div class="stack">${parties.map(p=>{const v=weightedMean(g.rows,`pct_${p.id}`,s.weight)??0;return `<i style="width:${v}%;background:${p.color}" title="${e(p.name)}: ${percent(v)}"></i>`;}).join('')}</div><small>n = ${number(g.rows.length)}</small></div>`).join('')}</div><div class="party-legend">${parties.map(p=>`<span><i style="background:${p.color}"></i>${p.id}</span>`).join('')}</div><div class="table-wrap">${table(bins)}</div>`;
 const cuts=Array.from({length:9},(_,i)=>quantile(national.map(d=>d.foreign_background_pct).filter(finite),(i+1)/10)??0);
 const deciles=Array.from({length:10},(_,i)=>({label:`${i+1} · ${percent(i===0?0:cuts[i-1])}–${percent(i===9?100:cuts[i])}`,rows:points.filter(d=>{let bin=cuts.findIndex(c=>d.foreign_background_pct!<=c);if(bin<0)bin=9;return bin===i;})}));
 root.querySelector('#deciles')!.innerHTML=table(deciles);
 root.querySelectorAll<SVGElement>('[data-district]').forEach(c=>{const click=()=>{const d=points.find(d=>d.district_id===c.dataset.district)!;root.querySelector('#point-detail')!.textContent=`${d.district_name} · ${d.municipality_name} | Origen extranjero ${percent(d.foreign_background_pct)} | ${ylabel} ${percent(d[key])} | ${number(d.valid_votes)} votos válidos`;select(d.district_id);};c.addEventListener('click',click);c.addEventListener('keydown',event=>{if(event.key==='Enter')click();});});
 const calculate=()=>{const included=[...root.querySelectorAll<HTMLInputElement>('input[name=predictor]:checked')].map(i=>i.value),complete=points.filter(d=>included.every(k=>finite(d[k]))),result=regression(complete.map(d=>included.map(k=>d[k] as number)),complete.map(d=>d[key] as number));root.querySelector('#regression-result')!.innerHTML=result?`<p>n = ${number(result.n)} · R² = ${number(result.r2,3)} · cada distrito pesa igual.</p><p class="meta">Coeficientes en puntos porcentuales de ${e(ylabel)} por una desviación típica de la variable explicativa, manteniendo las otras constantes. Sin pruebas de significación ni interpretación causal.</p><div class="table-wrap"><table><thead><tr><th>Variable</th><th>Coeficiente</th><th>Desviación típica original</th></tr></thead><tbody><tr><th>Intercepto (predictores centrados)</th><td>${number(result.coefficients[0],3)}</td><td>—</td></tr>${included.map((k,i)=>`<tr><th>${e(controlDefs.find(d=>d[0]===k)?.[1]??k)}</th><td>${number(result.coefficients[i+1],3)}</td><td>${number(result.sd[i],3)}</td></tr>`).join('')}</tbody></table></div>`:'<p>No se puede ajustar: selecciona predictores con variación, suficientes casos completos y sin colinealidad perfecta.</p>';};
 root.querySelectorAll('input[name=predictor]').forEach(input=>input.addEventListener('change',calculate));calculate();
}
