import {test,expect} from '@playwright/test';
test('country map uses municipal data, filters, proportions and CSV',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 await page.goto('countries/?country=SY&municipality=0180');
 await expect(page.locator('#country-map')).toHaveAttribute('data-ready','true',{timeout:30000});
 await expect(page.locator('#country-summary h2')).toHaveText('Stockholm');
 await expect(page.locator('.countries-intro')).toContainText('todos los residentes del municipio');
 await expect(page.locator('#birth-country option')).toHaveCount(188);
 await page.selectOption('#birth-country','ES');await expect(page.locator('.country-selected-label')).toContainText('España');
 await page.selectOption('#birth-county','12');await page.selectOption('#birth-municipality','1280');
 await expect(page.locator('#country-summary h2')).toHaveText('Malmö');
 await page.getByText('Todos los orígenes',{exact:true}).click();
 await page.locator('[data-birth-country="SY"]').click();await expect(page.locator('#birth-country')).toHaveValue('SY');
 expect(new URL(page.url()).searchParams.get('municipality')).toBe('1280');
 await page.reload();await expect(page.locator('#country-summary h2')).toHaveText('Malmö');
 const downloadPromise=page.waitForEvent('download');await page.click('#birth-download');expect((await downloadPromise).suggestedFilename()).toBe('paises-nacimiento-2025-1280.csv');
 await expect(page.locator('#country-map')).toHaveAttribute('data-ready','true',{timeout:30000});await expect.poll(async()=>Number(await page.locator('#country-map').getAttribute('data-features'))).toBeGreaterThan(0);await page.screenshot({path:'tests/artifacts/countries-desktop.png',fullPage:false});
 await page.setViewportSize({width:390,height:844});await page.goto('countries/?country=ES');await expect(page.locator('#country-map')).toHaveAttribute('data-ready','true',{timeout:30000});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('.country-map-area').scrollIntoViewIfNeeded();await expect.poll(async()=>Number(await page.locator('#country-map').getAttribute('data-features'))).toBeGreaterThan(0);await page.screenshot({path:'tests/artifacts/countries-mobile.png',fullPage:false});
 expect(errors).toEqual([]);
});

test('birth regions retain subtotal coverage, filters, URL and exports',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('countries/?country=SY&municipality=0180');
 await page.selectOption('#birth-grouping','regions');
 await expect(page.locator('#birth-country option')).toHaveCount(10);
 await expect(page.locator('#birth-country')).toHaveValue('REG_NON_EUROPE');
 await expect(page.locator('#birth-region-notice')).toBeVisible();
 await expect(page.locator('#birth-region-notice')).toContainText('No son totales continentales completos');
 await page.selectOption('#birth-country','REG_AFRICA');
 await expect(page.locator('.country-selected-label')).toContainText('África');
 await expect(page.locator('#country-summary .quality-note')).toContainText('celdas sin dato individual');
 await page.selectOption('#birth-county','12');await page.selectOption('#birth-municipality','1280');
 await expect(page.locator('#country-summary h2')).toHaveText('Malmö');
 await page.reload();await expect(page.locator('#birth-grouping')).toHaveValue('regions');
 await expect(page.locator('#birth-country')).toHaveValue('REG_AFRICA');
 const dl=page.waitForEvent('download');await page.click('#birth-download');
 const download=await dl;expect(download.suggestedFilename()).toBe('regiones-nacimiento-2025-1280.csv');
 const stream=await download.createReadStream();let csv='';for await(const chunk of stream!)csv+=chunk.toString();
 expect(csv).toContain('published_cell_subtotal');expect(csv).toContain('missing_country_count');expect(csv).toContain('REG_AFRICA');
 await expect(page.locator('#country-map')).toHaveAttribute('data-ready','true',{timeout:30000});
 await expect.poll(async()=>Number(await page.locator('#country-map').getAttribute('data-features'))).toBeGreaterThan(0);
 await page.screenshot({path:'tests/artifacts/birth-regions-desktop.png',fullPage:false});
 await page.locator('.country-notes>summary').click();await page.locator('.religion-note summary').click();
 await expect(page.locator('.religion-note')).toContainText('Sin datos municipales comparables');
 await page.setViewportSize({width:390,height:844});await page.goto('countries/?country=REG_ASIA');
 await expect(page.locator('#birth-grouping')).toHaveValue('regions');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('.country-map-area').scrollIntoViewIfNeeded();
 await expect(page.locator('#country-map')).toHaveAttribute('data-ready','true',{timeout:30000});
 await expect.poll(async()=>Number(await page.locator('#country-map').getAttribute('data-features'))).toBeGreaterThan(0);
 await page.screenshot({path:'tests/artifacts/birth-regions-mobile.png',fullPage:false});
 await page.selectOption('#birth-grouping','countries');await expect(page.locator('#birth-country option')).toHaveCount(188);
 await expect(page.locator('#birth-region-notice')).toBeHidden();expect(errors).toEqual([]);
});
