import {test,expect} from '@playwright/test';
test('DeSO birth estimates compare on electoral polygons, with definitions and CSV',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 await page.goto('./?year=2026&view=compare&metric=born_rest_world_unknown_pct&party=SD&municipality=0180');
 await expect(page.locator('#map-left')).toHaveAttribute('data-ready','true',{timeout:30000});
 await expect(page.locator('.maplibregl-canvas')).toHaveCount(2);
 await expect(page.locator('#metric')).toBeEnabled();
 await expect(page.locator('#map-left')).toHaveAttribute('data-metric','born_rest_world_unknown_pct');
 await expect(page.locator('#map-right')).toHaveAttribute('data-metric','pct_SD');
 await expect(page.locator('#left-caption')).toContainText('desconocido');
 await expect(page.locator('.district-birth-notice')).toContainText('Europa incluye Rusia y Turquía');
 await page.selectOption('#metric','born_europe_ex_sweden_pct');
 await expect(page.locator('#map-left')).toHaveAttribute('data-metric','born_europe_ex_sweden_pct');
 await expect(page.locator('#left-caption')).toContainText('Europa excepto Suecia');
 await page.selectOption('#party','S');await expect(page.locator('#map-right')).toHaveAttribute('data-metric','pct_S');
 await page.fill('#search','01801506');await page.click('#search-results [data-district="01801506"]');
 await expect(page.locator('#panel-content [data-district-history]')).toHaveAttribute('data-ready','true');
 await expect(page.locator('#panel-content [data-history-origin] .series-card')).toHaveCount(3);
 for(const group of await page.locator('#panel-content [data-history-origin] .series-card').all())await expect(group).toBeVisible();
 await page.locator('#comparison-detail').click();
 const birthRows=page.locator('#comparison-dialog .simple-data');await expect(birthRows).toHaveCount(2);
 for(const group of await birthRows.all())await expect(group).toBeHidden();
 await page.getByText('Población y nacimiento ≈',{exact:true}).click();
 for(const group of await birthRows.all())await expect(group).toBeVisible();
 await expect(page.locator('#comparison-dialog')).toContainText('nacimiento · 2025 · estimaciones');
 await page.locator('#close-comparison-dialog').click();
 await page.reload();await expect(page.locator('#metric')).toHaveValue('born_europe_ex_sweden_pct');
 await expect(page.locator('#panel-content')).toContainText('Katarina');
 const dl=page.waitForEvent('download');await page.click('#download');const stream=await (await dl).createReadStream();let csv='';for await(const chunk of stream!)csv+=chunk.toString();
 expect(csv).toContain('born_europe_ex_sweden_pct');expect(csv).toContain('birth_regions_source_url');expect(csv).toContain('birth_regions_method');
 await expect(page.locator('#map-left')).toHaveAttribute('data-ready','true',{timeout:30000});await page.screenshot({path:'tests/artifacts/district-birth-compare.png'});
 await page.click('[data-view=demography]');await expect(page.locator('#metric')).toHaveValue('born_europe_ex_sweden_pct');
 await page.selectOption('#metric','born_sweden_pct');await page.selectOption('#year','2022');
 await expect(page.locator('#map-left')).toHaveAttribute('data-metric','born_sweden_pct');
 await expect(page.locator('#map-left')).toHaveAttribute('data-year','2022');await expect(page.locator('#map-left')).toHaveAttribute('data-ready','true',{timeout:30000});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('.map-area').scrollIntoViewIfNeeded();await page.screenshot({path:'tests/artifacts/district-birth-mobile.png'});
 expect(errors).toEqual([]);
});
