import {test,expect} from '@playwright/test';
test('income has currency units, correct years, independent map scale and analysis axis',async({page})=>{
 await page.setViewportSize({width:1366,height:768});
 await page.goto('./?view=compare&municipality=2085&district=20850401&metric=mean_net_income&lang=en');
 await expect(page.locator('#map-left')).toHaveAttribute('data-ready','true');
 await expect(page.locator('#map-left')).toHaveAttribute('data-metric','mean_net_income');
 expect(Number(await page.locator('#map-left').getAttribute('data-scale-max'))).toBeGreaterThan(100000);
 await expect(page.locator('#left-caption')).toContainText('2024');await expect(page.locator('#legend')).toContainText('SEK/year');
 await expect(page.locator('.comparison-scope')).toContainText('Net income 2024');
 await expect(page.locator('#panel-content [data-district-history]')).toHaveAttribute('data-ready','true');
 await page.locator('#municipal-context').click();await expect(page.locator('#municipal-inline')).toHaveAttribute('data-ready','true');
 const top=(await page.locator('#municipal-inline').boundingBox())!.y;
 for(const bottom of await page.locator('#panel-content .series-card').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().bottom)))expect(bottom).toBeLessThanOrEqual(top);
 expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.setViewportSize({width:1024,height:768});
 expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const compactTop=(await page.locator('#municipal-inline').boundingBox())!.y;
 for(const bottom of await page.locator('#panel-content .series-card').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().bottom)))expect(bottom).toBeLessThanOrEqual(compactTop);
 await page.goto('./?view=demography&metric=mean_net_income&year=2022&lang=sv');
 await expect(page.locator('#map-left')).toHaveAttribute('data-ready','true');await expect(page.locator('#legend')).toContainText('2022');await expect(page.locator('#legend')).toContainText('SEK/år');
 await page.goto('./analysis/?year=2026&municipality=2085&analysisX=mean_net_income&party=S&lang=en');
 await expect(page.locator('#analysis-x')).toHaveValue('mean_net_income');await expect(page.locator('.scatter')).toContainText('thousand SEK/year');
 await expect(page.locator('.stat-strip')).toContainText('SEK 1,000');await expect(page.locator('.stat-strip')).toContainText('OLS slope');
 const xs=await page.locator('.scatter circle').evaluateAll(els=>els.map(el=>Number(el.getAttribute('cx'))));expect(xs.length).toBeGreaterThan(5);expect(xs.every(x=>x>=65&&x<=775)).toBe(true);
 await expect(page.locator('input[value=mean_net_income]')).toBeEnabled();
 await page.locator('#analysis-x').selectOption('born_rest_world_unknown_pct');await expect(page.locator('#analysis-x')).toHaveValue('born_rest_world_unknown_pct');
 await page.reload();await expect(page.locator('#analysis-x')).toHaveValue('born_rest_world_unknown_pct');
 await page.goto('./methodology/?lang=en');await expect(page.locator('#income')).toContainText('Mean annual net income');await expect(page.locator('#history')).toContainText('Electoral and population history');
 await expect(page.locator('article')).toContainText('2024 prices');await expect(page.locator('article')).toContainText('Solid lines connect available observations');
});
