import type {District,State} from '../types';
import {escapeHtml as e,number,percent} from '../utils/format';
import {hasVotes,voteSlices} from '../utils/cartogram';
import {partyBadge} from '../utils/categories';
import parties from '../../config/parties.json';
export function cartogramWorkspace(){return `<section class="atlas-workspace cartogram-workspace"><div class="cartogram-area"><header class="cartogram-heading"><div><h2>Votan las personas, no el territorio</h2><p>Cada círculo es un distrito. Su área representa sus votos válidos.</p></div><button id="cartogram-play" title="Animar las tres vistas">▶ Animar</button></header><div class="cartogram-controls" role="group" aria-label="Representación del voto"><button data-cartogram-mode="geography">1 · Superficie</button><button data-cartogram-mode="voters">2 · Votantes</button><button data-cartogram-mode="shares">3 · Todos los votos</button><button id="cartogram-reset">Centrar</button></div><p class="cartogram-explanation"></p><div class="cartogram-stage" aria-busy="true"><canvas id="cartogram-canvas" tabindex="0" aria-label="Cartograma electoral. Usa la búsqueda para seleccionar un distrito o consulta la tabla de votos."></canvas><div class="cartogram-status" role="status"></div><div class="cartogram-hover" hidden></div><div class="cartogram-zoom"><button data-cartogram-zoom="1.5" aria-label="Acercar">+</button><button data-cartogram-zoom="0.6666667" aria-label="Alejar">−</button></div></div><div class="cartogram-key"><div id="cartogram-color-key"></div><div class="cartogram-size-key"></div></div><footer class="cartogram-credit"><span>Inspirado en <a href="https://github.com/zumbov2/votemapswitzerland" target="_blank" rel="noreferrer">David Zumbach</a> y <a href="https://themorningnews.org/p/the-history-of-the-map-behind-land-doesnt-vote-people-do" target="_blank" rel="noreferrer">Karim Douïeb</a>.</span><a href="${import.meta.env.BASE_URL}methodology/#cartogram">Cómo se calcula</a></footer></div><aside class="side-panel"><button id="sheet-toggle" class="sheet-toggle" aria-expanded="true">Datos y rankings <span>⌃</span></button><div id="panel-content"></div></aside></section>`;}
export function cartogramPanel(rows:District[],state:State,selected?:District){
 const scope=selected?[selected]:rows,valid=scope.filter(hasVotes),total=valid.reduce((n,d)=>n+d.valid_votes!,0);
 const title=selected?selected.district_name:state.municipality?rows[0]?.municipality_name:state.county?rows[0]?.county_name:'Suecia';
 const counts=new Map<string,number>();for(const d of valid)for(const p of voteSlices(d))counts.set(p.id,(counts.get(p.id)??0)+p.votes);
 const results=[...parties,{id:'missing',name:'Sin desglose',color:'#7b8793'}].map(p=>({...p,votes:counts.get(p.id)??0})).filter(p=>p.id!=='missing'||p.votes>0);
 return `<div class="cartogram-results" data-vote-total="${total}"><header><div><span class="eyebrow">${state.year} · ${selected?e(selected.municipality_name):number(rows.length)+' distritos'}</span><h2>${e(title??'Sin distritos')}</h2></div>${selected?'<button id="close-district" aria-label="Cerrar ficha">×</button>':''}</header><div class="cartogram-vote-total"><strong>${number(total)}</strong><span>votos válidos</span></div><p class="cartogram-result-note">Porcentaje real de votos, sumando los distritos mostrados.</p><div class="cartogram-vote-bar" aria-hidden="true">${results.filter(p=>p.votes>0).map(p=>`<i style="flex:${p.votes};background:${p.color}"></i>`).join('')}</div><table class="cartogram-vote-table"><thead><tr><th>Partido</th><th>Votos</th><th>%</th></tr></thead><tbody>${results.sort((a,b)=>b.votes-a.votes).map(p=>`<tr><th scope="row">${p.id==='missing'?e(p.name):partyBadge(p.id)}</th><td>${number(p.votes)}</td><td>${total?percent(100*p.votes/total):'Sin dato'}</td></tr>`).join('')}</tbody></table><p class="cartogram-result-note">${number(scope.length-valid.length)} distritos sin votos válidos positivos; no tienen círculo.</p><button id="comparison-detail" class="comparison-detail-button">Ver detalle y evolución ↗</button><details class="cartogram-method"><summary>Qué representa</summary><p>El área, no el radio, es proporcional a los votos válidos. Los círculos se desplazan para no solaparse; sus posiciones son aproximadas.</p><p>El color del ganador no significa que todas las personas votaran por él. «Todos los votos» divide cada círculo según los votos de cada partido.</p><p>Se excluyen los votos tardíos y del exterior de las unidades sin geometría. Esta suma no equivale al resultado nacional completo.</p><p>Las vistas usan los mismos datos: cambia la representación, no el resultado.</p></details></div>`;
}
