import {partyLabel} from '../utils/party-selection';
import {isIncomeMetric,incomeAmount} from '../utils/income';
import type {District} from '../types';
import parties from '../../config/parties.json';
import {escapeHtml as e,percent} from '../utils/format';
import {partyBadge,blockWinner,districtOrigin,categoryLabel} from '../utils/categories';
import {demographicLabel} from '../utils/demography';
export function districtHover(d:District,metric:string){
 if(isIncomeMetric(metric))return `<article class="hover-card mini-hover" style="--accent:#278477"><header><h3>${e(d.district_name)}</h3><p>${e(d.municipality_name)}</p></header><section><div class="hover-section-title">Renta neta · ${d.income_year} ≈</div><div class="mini-value"><b>${incomeAmount(d.mean_net_income)}</b></div><small>Media personal · 20+ · precios de 2024.<br>Estimación DeSO → distrito.${d.income_complete===false?' Sin dato de algún área contribuyente.':''}</small></section><footer>Pulsa para ver el detalle</footer></article>`;
 const ranked=parties.filter(p=>p.id!=='other'&&typeof d['pct_'+p.id]==='number').sort((a,b)=>(d['pct_'+b.id] as number)-(d['pct_'+a.id] as number));
 const accent=parties.find(p=>p.id===d.winning_party)?.color??'#728694',origin=districtOrigin(d),block=blockWinner(d);
 const demographic=metric==='common_origin'||metric.startsWith('born_')||metric.startsWith('foreign_');
 const main=metric.startsWith('pct_')?`<div class="mini-value"><span>${e(partyLabel(metric.slice(4)))}</span><b>${percent(d[metric])}</b></div>`:metric==='winning_block'?`<div class="mini-value"><span>${e(categoryLabel('winning_block',block.code))}</span><b>${percent(block.pct)}</b></div>`:demographic?`<div class="mini-value"><span>${e(metric==='common_origin'?categoryLabel('common_origin',origin.code):demographicLabel(metric))}</span>${metric==='common_origin'?'':`<b>${percent(d[metric])}</b>`}</div>`:d.election_reported===false?'<div class="hover-pending">Recuento pendiente</div>':`${d.winning_party_tie?'<small>Empate en cabeza</small>':''}<div class="hover-runners">${ranked.slice(0,3).map(p=>`<div>${partyBadge(p.id)}<span>${percent(d['pct_'+p.id])}</span></div>`).join('')}</div>`;
 return `<article class="hover-card mini-hover" style="--accent:${accent}"><header><h3>${e(d.district_name)}</h3><p>${e(d.municipality_name)}</p></header><section><div class="hover-section-title"><span>${demographic?'Nacimiento · '+d.demography_year+' ≈':'Elecciones · '+d.election_year}</span>${!demographic&&d.election_status==='provisional'?'<span class="hover-tag">Provisional</span>':''}</div>${main}${demographic?`<small>${metric==='common_origin'?'Grupo predominante; excluye Suecia.':'% de todos los residentes.'} Estimación.${d.coverage_quality==='partial_coverage'?' Cobertura parcial.':''}</small>`:`<div class="mini-meta"><span>Participación</span><b>${percent(d.turnout_pct)}</b></div>${metric!=='winning_block'?`<div class="mini-meta"><span>Bloque líder</span><b>${e(categoryLabel('winning_block',block.code))}</b></div>`:''}`}</section><footer>Pulsa para ver el detalle</footer></article>`;
}
