import {categoryLabel,isCategorical,partyBadge,blockWinner,blockDefinitions} from '../utils/categories';
import type {District,State} from '../types';
import {parties} from '../maps/palette';
import {escapeHtml as e,number,percent,method} from '../utils/format';
import {value,finite,weightedMean,sum,turnout} from '../utils/data';
const fold=(title:string,content:string)=>`<details class="compact-detail"><summary>${title}</summary>${content}</details>`;
export function districtCard(d:District,all:District[],s:State){
 const v=value(d,s),ranked=all.filter(r=>finite(value(r,s))),rank=v===null?null:1+ranked.filter(r=>value(r,s)!>v).length;
 const bloc=blockWinner(d);
 const winners=`<div class="election-winners"><div><span>Partido más votado</span><strong>${d.election_reported===false?'Pendiente':d.winning_party_tie?'Empate':d.winning_party?partyBadge(d.winning_party):'Sin dato'}</strong></div><div><span>Bloque más votado</span><strong style="color:${blockDefinitions.find(b=>b.id===bloc.code)?.color??'#738594'}">${e(categoryLabel('winning_block',bloc.code))}</strong></div></div>`;
 const category=['electoral','compare'].includes(s.view)?winners:isCategorical(s.metric)?`<p class="selection-category"><span>${e(s.metric==='winning_block'?'Bloque más votado':s.metric==='common_origin'?'Origen predominante ≈':'Partido más votado')}</span><strong>${s.metric==='winning_party'&&d.winning_party?partyBadge(d.winning_party):''}${e(d.winning_party_tie&&s.metric==='winning_party'?'Empate':categoryLabel(s.metric,d[s.metric]))}</strong></p>`:'';
 const votes=`<h3>Votos · ${d.election_year}${d.election_status==='provisional'?' · provisional':''}</h3>${d.election_reported===false?'<p class="quality-note">Pendiente de recuento.</p>':''}<div class="vote-list">${parties.map(p=>`<div class="vote-row"><span title="${e(p.name)}">${partyBadge(p.id)}</span><div class="vote-track"><i style="width:${Number(d['pct_'+p.id])||0}%;background:${p.color}"></i></div><b>${percent(d['pct_'+p.id])}</b><small>${number(d['vote_'+p.id])}</small></div>`).join('')}</div>`;
 const birthCounts=[d.born_sweden_count,d.born_europe_ex_sweden_count,d.born_rest_world_unknown_count];
 const birthTotal=d.birth_regions_population;
 const birthSum=birthCounts.every(finite)?(birthCounts as number[]).reduce((sum,n)=>sum+n,0):null;
 const reconciliation=finite(birthTotal)&&birthSum!==null&&finite(d.birth_regions_sum_gap)&&Math.abs(d.birth_regions_sum_gap)>.05?fold('Por qué el desglose no suma 100 %',`<p>Los tres grupos suman ≈ ${number(birthSum)} personas y el total publicado, trasladado al distrito, es ≈ ${number(birthTotal)}. Hay un desajuste de ≈ ${number(Math.abs(d.birth_regions_sum_gap),1)} personas entre componentes y total. SCB protege las celdas por separado; se conserva esa diferencia y no se inventa un grupo para completarla.</p><p>«Nacidos fuera» se calcula como total menos nacidos en Suecia, incluido país desconocido. Por eso puede diferir de sumar Europa y resto. <a href="${e(d.birth_regions_source_url)}">Explicación de SCB ↗</a></p>`):'';
 const birth=`<p class="meta">${e(d.district_name)} · nacimiento · ${d.birth_regions_year} · estimaciones</p><div class="simple-data"><span>Suecia</span><b>${percent(d.born_sweden_pct)}</b><span>Europa excepto Suecia</span><b>${percent(d.born_europe_ex_sweden_pct)}</b><span>Resto + desconocido</span><b>${percent(d.born_rest_world_unknown_pct)}</b></div><p class="meta">% de ${number(d.birth_regions_population)} residentes estimados. Europa incluye Rusia y Turquía. Resto incluye país desconocido; no separa África y Asia. Las celdas protegidas pueden no sumar el total.</p>${reconciliation}<div class="simple-data"><span>Nacidos fuera¹ ≈</span><b>${percent(d.foreign_born_pct)}</b><span>Origen extranjero ≈</span><b>${percent(d.foreign_background_pct)}</b><span>Ciudadanía extranjera¹ ≈</span><b>${percent(d.foreign_citizens_pct)}</b></div><p class="meta">Origen extranjero incluye también a nacidos en Suecia con ambos progenitores nacidos fuera. Ciudadanía extranjera mide nacionalidad, no nacimiento. Son medidas distintas; no se suman.</p>`;
 const comparison=`<p class="meta">${e(({comparable:'Distritos comparables',comparable_aggregate:'Comparable con dos distritos agrupados',not_comparable:'Sin comparación válida',source_disagreement:'Discrepancia entre fuentes'} as Record<string,string>)[String(d.comparison_status)]??'Sin comparación')}<br>Distritos 2022: ${e(d.comparison_old_ids??'—')}<br>Δ S: ${number(d.delta_pct_S,2)} pp · Δ SD: ${number(d.delta_pct_SD,2)} pp<br>Δ M: ${number(d.delta_pct_M,2)} pp · Δ participación: ${number(d.delta_turnout_pct,2)} pp</p>`;
 const quality=`<p class="meta">${e(method(d.demography_method))}<br>Estadística ${d.demography_year} · DeSO ${d.demography_geometry_year} · límites ${d.geometry_year}.<br>Cobertura geométrica: ${percent(d.demography_coverage*100)}<br>Completitud: ${percent(d.demography_data_coverage*100)}<br>DeSO dominante: ${percent(d.dominant_overlap_share*100)}<br>Cobertura de asignación: ${percent(d.source_allocation_coverage*100)}<br>Una cobertura alta no garantiza precisión local.</p><p class="meta">Electores: ${number(d.eligible_voters)} · Votantes: ${number(d.ballots_cast)}<br>Educación postsecundaria, 25–64 (${d.education_year??'sin dato'}): ≈ ${percent(d.higher_education_pct)}<br>Empleo, 20–64 (${d.employment_year??'sin dato'}): ≈ ${percent(d.employment_pct)}<br>¹ Nacimiento incluye país desconocido; ciudadanía incluye apátridas y desconocida.</p>${!isCategorical(s.metric)?`<p class="meta">Ranking: ${number(rank)} de ${number(ranked.length)}.</p>`:''}<a href="${e(d.election_source_url)}" target="_blank" rel="noreferrer">Fuente electoral ↗</a>`;
 return `<div class="card-title"><span class="eyebrow">DISTRITO · ${e(d.district_id)}</span><button id="close-district" aria-label="Cerrar ficha">×</button></div><h2>${e(d.district_name)}</h2><p class="meta">${e(d.municipality_name)}</p><section class="district-history" data-district-history aria-label="Evolución de votos y origen poblacional"></section><section class="district-current" aria-label="Datos actuales del distrito"><header class="scope-heading"><span class="scope-chip">Distrito</span><h3>${e(d.district_name)}</h3><p>≈ ${number(d.population)} residentes · población ${d.demography_year}</p></header>${category}<div class="district-stat"><div><span>Participación · ${d.election_year}</span><b>${percent(d.turnout_pct)}</b></div><div><span>Origen extranjero ≈</span><b>${percent(d.foreign_background_pct)}</b></div></div>${fold('Votos del distrito · '+d.election_year,votes)}${fold('Población y nacimiento ≈',birth)}${d.comparison_status?fold('Cambio desde 2022',comparison):''}${fold('Fuentes y precisión',quality)}</section><section class="municipal-context" data-municipal-context aria-label="Composición del municipio completo"></section>`;
}
export function summary(rows:District[],s:State){
 const categorical=isCategorical(s.metric),pending=rows.filter(d=>d.election_reported===false).length;
 const votes=`<h3>Voto medio por partido</h3><p class="meta">${s.weight==='votes'?'Ponderado por votos válidos':'Cada distrito pesa igual'}</p><div class="vote-list">${parties.map(p=>{const v=weightedMean(rows,'pct_'+p.id,s.weight);return `<div class="vote-row summary-vote"><span>${partyBadge(p.id)}</span><div class="vote-track"><i style="width:${v??0}%;background:${p.color}"></i></div><b>${percent(v)}</b></div>`;}).join('')}</div>`;
 return `<span class="eyebrow">${s.year} · ${number(rows.length)} distritos</span><h2>${s.municipality?e(rows[0]?.municipality_name??'Sin distritos'):s.county?e(rows[0]?.county_name??'Sin distritos'):'Suecia'}</h2><div class="district-stat"><div><span>Participación</span><b>${percent(turnout(rows))}</b></div><div><span>Población ≈</span><b>${number(sum(rows,'population'))}</b></div></div>${pending?`<p class="meta">${number(pending)} distritos pendientes.</p>`:''}${categorical?fold('Voto por partido',votes):votes}${fold('Cómo se calcula',`<p class="meta">Participación agregada sobre distritos con votantes y electores conocidos. Excluye unidades de recogida; no equivale al resultado nacional completo. ${number(rows.filter(d=>d.coverage_quality==='partial_coverage').length)} distritos con cobertura parcial. La demografía es estimada; consulta la fuente y el año de cada ficha.</p>`)}`;
}
